### ISSUE TITLE
커서 위치 계산 시, 매직 넘버를 제거하고 radian을 적용해주세요.

### ISSUE THREAD

**Issue by libqwerty** [noname0310/Chippy-Keyboard-Aiming-Controller#1]
https://github.com/noname0310/Chippy-Keyboard-Aiming-Controller/blob/d9d835dbd81c6d1d9172e1495486dc89e9f6592c/ChippyController/ChippyController/MainForm.cs#L45-L59

커서가 원을 그리며 회전하도록 하는 동작인데, 매직넘버 `57` 대신 호도법(radian)을 적용 해주세요.

**Comment by noname0310** [comment]
https://github.com/noname0310/Chippy-Keyboard-Aiming-Controller/commit/932423214c719b6f8cc2d54a2f2427af315201fd
수정 했습니다
